### ISSUE TITLE
TGA Normal Map

### ISSUE THREAD

**Issue by hemeac** [CiXwOw/KSP-SciencePancake#1]
I noticed that my KSP log was throwing an error when it was trying to find the normal map.  Everything was referenced correctly, but it does not seem to like tga for normal maps.  I converted it to a png and that seems to solved the issue.

**Comment by Drew2473399** [comment]
Thanks for pointing this out! I'll do some research on formats for normal maps later!

**Comment by CiXwOw** [comment]
Thanks for pointing this out! I'll do some research on formats for normal maps later!

**Comment by CiXwOw** [comment]
@hemeac I haven't been able to find the log error you mentioned, could you please post yours?
I've done some research and testing, and converted the tga files to dds, however I'm assuming I've done something wrong as the lighting was all messed up with the new textures.
If I could see the error message you're getting (as well as the version of KSP you're using) perhaps I could get a better understanding of the issue.
EDIT: I've narrowed the lighting issue to the normal map. I'm still investigating what could be causing it.

**Comment by hemeac** [comment]
That does not seem to be a reproduceable error, so I am not quite sure why it threw the error yesterday, but it is working fine now.   Apologize for wasting your time.  Both times it was in 1.9.1.

**Comment by CiXwOw** [comment]
No worries, was happy to look into it!
I'll likely still update to dds textures once I can figure out the right settings as while investigating this issue I found it's considered best practice for release assets.
